# Generated by Django 4.2.28 on 2026-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь'), (13, 'Ежегодная инфляция')], verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('inflation_value', models.FloatField(verbose_name='Значение инфляции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инфляция',
                'verbose_name_plural': 'Инфляция по месяцам',
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
