# Generated by Django 4.2.28 on 2026-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('Денежные доходы', 'Денежные доходы'), ('Оплата труда', 'Оплата труда'), ('Социальные выплаты', 'Социальные выплаты'), ('Доходы от предпринимательства', 'Доходы от предпринимательства'), ('Доходы от собственности', 'Доходы от собственности'), ('Другие доходы', 'Другие доходы'), ('Потребительские расходы', 'Потребительские расходы'), ('Обязательные платежи', 'Обязательные платежи')], max_length=100, verbose_name='Показатель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доходы и расходы',
                'verbose_name_plural': 'Доходы и расходы',
                'ordering': ['year', 'indicator'],
                'unique_together': {('indicator', 'year')},
            },
        ),
    ]
