# Generated by Django 4.2.28 on 2026-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0002_incomeexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Доля в %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доля населения с доходами',
                'verbose_name_plural': 'Доля населения с денежными доходами',
                'ordering': ['year'],
            },
        ),
    ]
