# Generated by Django 4.2.28 on 2026-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0003_incomeshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseIncidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(choices=[('absolute', 'Абсолютные значения'), ('per_1000', 'На 1000 человек')], max_length=20, verbose_name='Тип таблицы')),
                ('indicator', models.CharField(max_length=200, verbose_name='Показатель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заболеваемость',
                'verbose_name_plural': 'Заболеваемость населения',
                'ordering': ['table_type', 'year', 'indicator'],
                'unique_together': {('table_type', 'indicator', 'year')},
            },
        ),
    ]
