# Generated by Django 4.2.28 on 2026-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation', '0004_diseaseincidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_type', models.CharField(choices=[('doctors', 'Врачи'), ('nursing', 'Средний медперсонал')], max_length=20, verbose_name='Тип персонала')),
                ('value_type', models.CharField(choices=[('total', 'Абсолютное значение'), ('per_10000', 'На 10000 человек')], max_length=20, verbose_name='Тип значения')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Медицинские кадры',
                'verbose_name_plural': 'Численность медицинских кадров',
                'ordering': ['personnel_type', 'year'],
                'unique_together': {('personnel_type', 'value_type', 'year')},
            },
        ),
    ]
